### PR TITLE
Mj pages layout

### PR DESCRIPTION
**Pull request by manfredjoa**

### CODE REVIEW

**Review by manfredjoa — COMMENTED** [review]
Movies page does not seem like it is working 100%
UPDATE: fixed

**Review by manfredjoa — COMMENTED** [review]
I can start working on making reusable components so that the components are not so verbose and hard to read. There are a lot of commonalities between all these components that can allow for reusability.

**Review by manfredjoa — COMMENTED** [review]
If there are 0 search results, the LoadingBars component will be displayed. We should have a message saying that no results were found.

**Review by manfredjoa — COMMENTED** [review]
Error from a missing key attribute in the map function prevents npm run build from running.

**Review by alantothe — APPROVED** [review]
good

**Pull request merged**
